// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uEuFdHfPnROJeso8A-PsTZPAjsVMcaU',
    appId: '1:25562651801:android:a1c7e08558f96ccc672c08',
    messagingSenderId: '25562651801',
    projectId: 'job-task-project-46da6',
    storageBucket: 'job-task-project-46da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5QiVPoniRyozO3FvuSpRS1ecQClxSLs',
    appId: '1:25562651801:ios:1d9f0dd8338e208d672c08',
    messagingSenderId: '25562651801',
    projectId: 'job-task-project-46da6',
    storageBucket: 'job-task-project-46da6.firebasestorage.app',
    androidClientId: '25562651801-dvjkff2e5l0bobfeaeaokqpcif7iv105.apps.googleusercontent.com',
    iosClientId: '25562651801-ueg816kujc1kdjt4o805c6pqoh1v9gmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTask',
  );

}